title: Mica Li
baseurl: "https://li-michelle.github.io"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "https://li.michelle.github.io"
 - name: "Resume"
   link: "CV.pdf"
 - name: "Contact"
   link: "contact"
